package VISTAS;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Heber Gomez
 */
public class grados extends javax.swing.JFrame {

    /**
     * Creates new form grados
     */
    public grados () {
        initComponents();
        setTitle("Conversor de Grados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        CONVERSOR = new javax.swing.JLabel();
        jLabel2INGRESARTEMP = new javax.swing.JLabel();
        jTextField1INTRODUCIRVALOR = new javax.swing.JTextField();
        jButton1CONVERTIDOR = new javax.swing.JButton();
        jRadioButton1OP = new javax.swing.JRadioButton();
        jRadioButton4OP = new javax.swing.JRadioButton();
        jRadioButton2OP = new javax.swing.JRadioButton();
        jRadioButton3OP = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDoubleBuffered(false);

        CONVERSOR.setText("CONVERSOR DE TEMPERATURA");

        jLabel2INGRESARTEMP.setText("INGRESO DE TEMPERATURA EN GRADOS");

        jTextField1INTRODUCIRVALOR.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1INTRODUCIRVALOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1INTRODUCIRVALORActionPerformed(evt);
            }
        });

        jButton1CONVERTIDOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconos netbeans/icons8-aprobar-y-actualizar-48.png"))); // NOI18N
        jButton1CONVERTIDOR.setText("CONVERTIR");
        jButton1CONVERTIDOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CONVERTIDORActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1OP);
        jRadioButton1OP.setText("A Fahrenheit");
        jRadioButton1OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1OPActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4OP);
        jRadioButton4OP.setText("A Radianes");

        buttonGroup1.add(jRadioButton2OP);
        jRadioButton2OP.setText("A Celsius");
        jRadioButton2OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2OPActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3OP);
        jRadioButton3OP.setText("A Kelvin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(CONVERSOR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton3OP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton1OP, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton2OP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton4OP, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                            .addComponent(jLabel2INGRESARTEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton1CONVERTIDOR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jTextField1INTRODUCIRVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CONVERSOR)
                .addGap(45, 45, 45)
                .addComponent(jLabel2INGRESARTEMP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1INTRODUCIRVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1OP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2OP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3OP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4OP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1CONVERTIDOR)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2OPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2OPActionPerformed

    private void jButton1CONVERTIDORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CONVERTIDORActionPerformed
        try {
            double valor = Double.parseDouble(jTextField1INTRODUCIRVALOR.
                getText());
            double resultado = 0;
            if (jRadioButton1OP.isSelected()) {
                resultado = valor * 9 / 5 + 32;
                JOptionPane.showMessageDialog(this,
                    "La Temperatura en Grados Fahrenheit es:" + resultado);
            }
            else if (jRadioButton2OP.isSelected()) {
                resultado = valor;
                JOptionPane.showMessageDialog(this,
                    "La Temperatura en Grados Celsius es:" + resultado);
            }
            else if (jRadioButton3OP.isSelected()) {
                resultado = valor + 273.15;
                JOptionPane.showMessageDialog(this,
                    "La Temperatura en Grados Kelvins es:" + resultado);
            }
            else if (jRadioButton4OP.isSelected()) {
                resultado = valor * (Math.PI / 180);
                JOptionPane.showMessageDialog(this,
                    "La Temperatura en Grados Radianes es:" + resultado);
            }
            else {
                JOptionPane.showMessageDialog(this,
                    "no Seleccionaste ni una Opcion:");
            }
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Por Favor Ingrese un valor Numerico");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1CONVERTIDORActionPerformed

    private void jTextField1INTRODUCIRVALORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1INTRODUCIRVALORActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jTextField1INTRODUCIRVALORActionPerformed

    private void jRadioButton1OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1OPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1OPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grados.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grados.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grados.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grados.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run () {
                new grados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONVERSOR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1CONVERTIDOR;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2INGRESARTEMP;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1OP;
    private javax.swing.JRadioButton jRadioButton2OP;
    private javax.swing.JRadioButton jRadioButton3OP;
    private javax.swing.JRadioButton jRadioButton4OP;
    private javax.swing.JTextField jTextField1INTRODUCIRVALOR;
    // End of variables declaration//GEN-END:variables
}
